# Generated by Django 5.1.1 on 2024-10-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=64)),
                ('userName', models.CharField(max_length=30)),
                ('screenName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenName', models.CharField(max_length=20)),
                ('userEmail', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=64)),
                ('userName', models.CharField(max_length=30)),
                ('screenName', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=25)),
                ('userGender', models.IntegerField()),
                ('userDOB', models.IntegerField()),
            ],
        ),
    ]
