# Generated by Django 5.1.1 on 2024-10-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='AdminUser',
        ),
        migrations.RenameModel(
            old_name='blacklist',
            new_name='BlacklistedUser',
        ),
    ]
