# Generated by Django 5.1.1 on 2024-10-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_admin_adminuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userDOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(max_length=64),
        ),
    ]
