# Generated by Django 5.1.1 on 2024-10-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_userdob_alter_user_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
