# Generated by Django 5.1.1 on 2024-10-24 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_screenname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.IntegerField(default=8392513283, primary_key=True, serialize=False, unique=True)),
                ('userEmail', models.EmailField(max_length=99, null=True, unique=True)),
                ('postID', models.IntegerField(default=6812413, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('likeCount', models.IntegerField(null=True)),
                ('dislikeCount', models.IntegerField(null=True)),
                ('docPost', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='blacklisteduser',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='screenName',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='blacklisteduser',
            name='screenName',
        ),
        migrations.AddField(
            model_name='user',
            name='docAcct',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.IntegerField(default=8392513283, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='userEmail',
            field=models.EmailField(max_length=99, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blacklisteduser',
            name='id',
            field=models.IntegerField(default=8392513283, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blacklisteduser',
            name='userEmail',
            field=models.EmailField(max_length=99, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=8392513283, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=2896528, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userDOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(max_length=99, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userGender',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPassword',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
