# Generated by Django 5.1.1 on 2024-10-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_postinteraction_alter_adminuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.IntegerField(default=8820747815, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='userEmail',
            field=models.EmailField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='blacklisteduser',
            name='id',
            field=models.IntegerField(default=8820747815, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blacklisteduser',
            name='userEmail',
            field=models.EmailField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='id',
            field=models.IntegerField(default=8820747815, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='postID',
            field=models.IntegerField(default=9673772, unique=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='userEmail',
            field=models.EmailField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=8820747815, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=6405636, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(max_length=99, null=True),
        ),
    ]
