# Generated by Django 5.1.1 on 2024-10-24 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_delete_adminuser_delete_blacklisteduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='docAcct',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.IntegerField(default=1185678881, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=8027633406, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=3666322, max_length=20, unique=True),
        ),
    ]
