# Generated by Django 5.1.1 on 2024-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_adminuser_id_alter_adminuser_useremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.IntegerField(default=4727185233, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blacklisteduser',
            name='id',
            field=models.IntegerField(default=4727185233, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='id',
            field=models.IntegerField(default=4727185233, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='postID',
            field=models.IntegerField(default=5308869, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=4727185233, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=9682985, max_length=20, unique=True),
        ),
    ]
