# Generated by Django 5.1.1 on 2024-10-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_adminuser_id_alter_blacklisteduser_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='BlacklistedUser',
        ),
        migrations.AlterModelOptions(
            name='postinteraction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='postinteraction',
            name='userEmail',
        ),
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='dislikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postinteraction',
            name='postID',
            field=models.IntegerField(default=8174774590, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=4333005901, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=4255424, max_length=20, unique=True),
        ),
    ]
