# Generated by Django 5.1.1 on 2024-10-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_adminuser_delete_blacklisteduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraction',
            name='postID',
            field=models.IntegerField(default=2880730346, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=1802155158, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=3814226, max_length=20, unique=True),
        ),
    ]
