# Generated by Django 5.1.1 on 2024-11-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_post_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='post',
            name='postURL',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.IntegerField(default=1584547113, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=7679972200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=5493442, max_length=20, unique=True),
        ),
    ]
