# Generated by Django 5.1.1 on 2024-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_post_options_post_posturl_alter_post_postid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followList',
            field=models.CharField(max_length=999, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.IntegerField(default=9338945791, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=6982276946, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=7346925, max_length=20, unique=True),
        ),
    ]
