# Generated by Django 5.1.1 on 2024-10-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_postinteraction_postid_alter_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.IntegerField(default=8121578773, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('likeCount', models.IntegerField(default=0)),
                ('dislikeCount', models.IntegerField(default=0)),
                ('docPost', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PostInteraction',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=6401791365, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=9678788, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
