# Generated by Django 5.1.1 on 2024-11-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_post_postid_alter_post_user_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userPfp',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.IntegerField(default=6373126370, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=9415315390, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=5562449, max_length=20, unique=True),
        ),
    ]
