# Generated by Django 5.1.1 on 2024-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_post_userpfp_alter_post_postid_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=4670876563, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default=1916047, max_length=20, unique=True),
        ),
    ]
