# Generated by Django 5.1.1 on 2024-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_id_alter_user_screenname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='screenName',
            field=models.CharField(default='6164184c', max_length=20, unique=True),
        ),
    ]
