# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "test" ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd frontend
    - run: rm -rf package-lock.json node_modules
    # - run: npm install jest --save-dev
    # - run: npm install @babel/preset-react --save-dev
    # - run: npm install @testing-library/react --save-dev
    # - run: npm install @fortawesome/react-fontawesome --save-dev
    # - run: npm install @emotion/styled --save-dev
    # - run: npm install react-router-dom --save-dev
    # - run: npm install --save-dev jest-environment-jsdom
    # - run: npm install @testing-library/jest-dom --save-dev
    # - run: npm install firebase
    - run: npm install @babel/plugin-proposal-private-property-in-object@7.21.11
    - run: npm install @emotion/react@11.13.3
    - run: npm install @emotion/styled@11.13.0
    - run: npm install @fortawesome/fontawesome-free@6.6.0
    - run: npm install @fortawesome/fontawesome-svg-core@6.7.1
    - run: npm install @fortawesome/free-solid-svg-icons@6.6.0
    - run: npm install @fortawesome/react-fontawesome@0.2.2
    - run: npm install @mui/icons-material@6.1.2
    - run: npm install @mui/material@6.1.2
    - run: npm install @testing-library/jest-dom@5.17.0
    - run: npm install @testing-library/react@13.4.0
    - run: npm install @testing-library/user-event@13.5.0
    - run: npm install autoprefixer@10.4.20
    - run: npm install axios@1.7.7
    - run: npm install firebase@11.0.2
    - run: npm install postcss@8.4.47
    - run: npm install react-dom@18.3.1
    - run: npm install react-player@2.16.0
    - run: npm install react-router-dom@6.26.2
    - run: npm install react-scripts@5.0.1
    - run: npm install react@18.3.1
    - run: npm install tailwindcss@3.4.13
    - run: npm install uuid@11.0.3
    - run: npm install node-fetch
    - run: npm install text-encoding
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
