name: Node.js CI

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd frontend
    - run: rm -rf package-lock.json node_modules
    - run: npm install --legacy-peer-deps
    # Install all necessary dependencies
    - run: npm install @babel/plugin-proposal-private-property-in-object@7.21.11 --legacy-peer-deps
    - run: npm install @emotion/react@11.13.3 --legacy-peer-deps
    - run: npm install @emotion/styled@11.13.0 --legacy-peer-deps
    - run: npm install @fortawesome/fontawesome-free@6.6.0 --legacy-peer-deps
    - run: npm install @fortawesome/fontawesome-svg-core@6.7.1 --legacy-peer-deps
    - run: npm install @fortawesome/free-solid-svg-icons@6.6.0 --legacy-peer-deps
    - run: npm install @fortawesome/react-fontawesome@0.2.2 --legacy-peer-deps
    - run: npm install @mui/icons-material@6.1.2 --legacy-peer-deps
    - run: npm install @mui/material@6.1.2 --legacy-peer-deps
    - run: npm install @testing-library/jest-dom@5.17.0 --legacy-peer-deps
    - run: npm install @testing-library/react@13.4.0 --legacy-peer-deps
    - run: npm install @testing-library/user-event@13.5.0 --legacy-peer-deps
    - run: npm install autoprefixer@10.4.20 --legacy-peer-deps
    - run: npm install axios@1.7.7 --legacy-peer-deps
    - run: npm install firebase@11.0.2 --legacy-peer-deps
    - run: npm install postcss@8.4.47 --legacy-peer-deps
    - run: npm install react-dom@18.3.1 --legacy-peer-deps
    - run: npm install react-player@2.16.0 --legacy-peer-deps
    - run: npm install react-router-dom@6.26.2 --legacy-peer-deps
    - run: npm install react-scripts@5.0.1 --legacy-peer-deps
    - run: npm install react@18.3.1 --legacy-peer-deps
    - run: npm install tailwindcss@3.4.13 --legacy-peer-deps
    - run: npm install uuid@11.0.3 --legacy-peer-deps
    - run: npm install node-fetch --legacy-peer-deps
    - run: npm install text-encoding --legacy-peer-deps
    # Run CI commands
    - run: npm ci --legacy-peer-deps
    - run: npm run build --if-present
    - run: npm test
